name: Deploy flask App

on:
    workflow_dispatch:
    workflow_run:
        workflows: ["Docker Build and Push"]
        types:
            - completed
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted
        env:
            DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
            DOCKER_TAG: ${{ github.sha }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup docker compose
              uses: docker/setup-compose-action@v2

            - name: Deploy with docker compose
              run: |
                    sudo apt-get update && sudo apt-get install -y docker.io docker-compose-v2
                    sudo usermod -aG docker $USER
                    newgrp docker
                    sudo chmod 666 /var/run/docker.sock
                    docker compose down -v &&docker compose up -d --build --force-recreate --pull always
                