name: Deploy flask App

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted
        env:
            DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy with docker compose
              run: docker compose -f docker-compose.yml up -d
                