name: Docker lint

on:
    workflow_call:

jobs:
    validate-dockerfile:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: lint Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile